// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/models.dart';
import 'api/ocr.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  PaperBook dco_decode_box_autoadd_paper_book(dynamic raw);

  @protected
  PaperPage dco_decode_box_autoadd_paper_page(dynamic raw);

  @protected
  PdfDoc dco_decode_box_autoadd_pdf_doc(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Note> dco_decode_list_note(dynamic raw);

  @protected
  List<OcrPage> dco_decode_list_ocr_page(dynamic raw);

  @protected
  List<PaperBook> dco_decode_list_paper_book(dynamic raw);

  @protected
  List<PaperPage> dco_decode_list_paper_page(dynamic raw);

  @protected
  List<PdfDoc> dco_decode_list_pdf_doc(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  OcrError dco_decode_ocr_error(dynamic raw);

  @protected
  OcrPage dco_decode_ocr_page(dynamic raw);

  @protected
  OcrResult dco_decode_ocr_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PaperBook dco_decode_paper_book(dynamic raw);

  @protected
  PaperBooksData dco_decode_paper_books_data(dynamic raw);

  @protected
  PaperPage dco_decode_paper_page(dynamic raw);

  @protected
  PdfDoc dco_decode_pdf_doc(dynamic raw);

  @protected
  PdfDocsData dco_decode_pdf_docs_data(dynamic raw);

  @protected
  StorageError dco_decode_storage_error(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  PaperBook sse_decode_box_autoadd_paper_book(SseDeserializer deserializer);

  @protected
  PaperPage sse_decode_box_autoadd_paper_page(SseDeserializer deserializer);

  @protected
  PdfDoc sse_decode_box_autoadd_pdf_doc(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer);

  @protected
  List<OcrPage> sse_decode_list_ocr_page(SseDeserializer deserializer);

  @protected
  List<PaperBook> sse_decode_list_paper_book(SseDeserializer deserializer);

  @protected
  List<PaperPage> sse_decode_list_paper_page(SseDeserializer deserializer);

  @protected
  List<PdfDoc> sse_decode_list_pdf_doc(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  OcrError sse_decode_ocr_error(SseDeserializer deserializer);

  @protected
  OcrPage sse_decode_ocr_page(SseDeserializer deserializer);

  @protected
  OcrResult sse_decode_ocr_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PaperBook sse_decode_paper_book(SseDeserializer deserializer);

  @protected
  PaperBooksData sse_decode_paper_books_data(SseDeserializer deserializer);

  @protected
  PaperPage sse_decode_paper_page(SseDeserializer deserializer);

  @protected
  PdfDoc sse_decode_pdf_doc(SseDeserializer deserializer);

  @protected
  PdfDocsData sse_decode_pdf_docs_data(SseDeserializer deserializer);

  @protected
  StorageError sse_decode_storage_error(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_paper_book(
    PaperBook self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_paper_page(
    PaperPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pdf_doc(PdfDoc self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ocr_page(List<OcrPage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_paper_book(
    List<PaperBook> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_paper_page(
    List<PaperPage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pdf_doc(List<PdfDoc> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_error(OcrError self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_page(OcrPage self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_result(OcrResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_paper_book(PaperBook self, SseSerializer serializer);

  @protected
  void sse_encode_paper_books_data(
    PaperBooksData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paper_page(PaperPage self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_doc(PdfDoc self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_docs_data(PdfDocsData self, SseSerializer serializer);

  @protected
  void sse_encode_storage_error(StorageError self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
