// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/models.dart';
import 'api/ocr.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1345491495;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_brrk',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiStorageClearOcrCache();

  Future<void> crateApiStorageDeleteNote({
    required String pageId,
    required String noteId,
  });

  Future<void> crateApiStorageDeletePaperBook({required String bookId});

  Future<void> crateApiStorageDeletePaperPage({
    required String bookId,
    required String pageId,
    required String updatedAt,
  });

  Future<void> crateApiStorageDeletePdfDoc({required String docId});

  Future<PaperBooksData> crateApiStorageGetPaperBooks();

  Future<PdfDocsData> crateApiStorageGetPdfDocs();

  Future<String> crateApiStorageGetPdfMarkdown({required String docId});

  void crateApiStorageInitApp({required String dataDir});

  Future<PaperBooksData> crateApiModelsPaperBooksDataDefault();

  Future<PdfDocsData> crateApiModelsPdfDocsDataDefault();

  Future<OcrResult> crateApiOcrProcessImage({
    required String base64Data,
    required String fileName,
    required String apiKey,
    required bool forceRefresh,
  });

  Future<OcrResult> crateApiOcrProcessPdf({
    required String docId,
    required String fileName,
    required String apiKey,
    required bool forceRefresh,
  });

  Future<void> crateApiStorageSaveNote({
    required String pageId,
    required Note note,
  });

  Future<void> crateApiStorageSavePaperBook({required PaperBook book});

  Future<void> crateApiStorageSavePdfDoc({required PdfDoc doc});

  Future<void> crateApiStorageUpsertPaperPage({
    required String bookId,
    required PaperPage page,
    required String updatedAt,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiStorageClearOcrCache() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageClearOcrCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageClearOcrCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_ocr_cache", argNames: []);

  @override
  Future<void> crateApiStorageDeleteNote({
    required String pageId,
    required String noteId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pageId, serializer);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageDeleteNoteConstMeta,
        argValues: [pageId, noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeleteNoteConstMeta => const TaskConstMeta(
    debugName: "delete_note",
    argNames: ["pageId", "noteId"],
  );

  @override
  Future<void> crateApiStorageDeletePaperBook({required String bookId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bookId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageDeletePaperBookConstMeta,
        argValues: [bookId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeletePaperBookConstMeta =>
      const TaskConstMeta(debugName: "delete_paper_book", argNames: ["bookId"]);

  @override
  Future<void> crateApiStorageDeletePaperPage({
    required String bookId,
    required String pageId,
    required String updatedAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bookId, serializer);
          sse_encode_String(pageId, serializer);
          sse_encode_String(updatedAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageDeletePaperPageConstMeta,
        argValues: [bookId, pageId, updatedAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeletePaperPageConstMeta =>
      const TaskConstMeta(
        debugName: "delete_paper_page",
        argNames: ["bookId", "pageId", "updatedAt"],
      );

  @override
  Future<void> crateApiStorageDeletePdfDoc({required String docId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageDeletePdfDocConstMeta,
        argValues: [docId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeletePdfDocConstMeta =>
      const TaskConstMeta(debugName: "delete_pdf_doc", argNames: ["docId"]);

  @override
  Future<PaperBooksData> crateApiStorageGetPaperBooks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paper_books_data,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageGetPaperBooksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetPaperBooksConstMeta =>
      const TaskConstMeta(debugName: "get_paper_books", argNames: []);

  @override
  Future<PdfDocsData> crateApiStorageGetPdfDocs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_docs_data,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageGetPdfDocsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetPdfDocsConstMeta =>
      const TaskConstMeta(debugName: "get_pdf_docs", argNames: []);

  @override
  Future<String> crateApiStorageGetPdfMarkdown({required String docId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageGetPdfMarkdownConstMeta,
        argValues: [docId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageGetPdfMarkdownConstMeta =>
      const TaskConstMeta(debugName: "get_pdf_markdown", argNames: ["docId"]);

  @override
  void crateApiStorageInitApp({required String dataDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageInitAppConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: ["dataDir"]);

  @override
  Future<PaperBooksData> crateApiModelsPaperBooksDataDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paper_books_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsPaperBooksDataDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsPaperBooksDataDefaultConstMeta =>
      const TaskConstMeta(debugName: "paper_books_data_default", argNames: []);

  @override
  Future<PdfDocsData> crateApiModelsPdfDocsDataDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_docs_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsPdfDocsDataDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsPdfDocsDataDefaultConstMeta =>
      const TaskConstMeta(debugName: "pdf_docs_data_default", argNames: []);

  @override
  Future<OcrResult> crateApiOcrProcessImage({
    required String base64Data,
    required String fileName,
    required String apiKey,
    required bool forceRefresh,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base64Data, serializer);
          sse_encode_String(fileName, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_bool(forceRefresh, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ocr_result,
          decodeErrorData: sse_decode_ocr_error,
        ),
        constMeta: kCrateApiOcrProcessImageConstMeta,
        argValues: [base64Data, fileName, apiKey, forceRefresh],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOcrProcessImageConstMeta => const TaskConstMeta(
    debugName: "process_image",
    argNames: ["base64Data", "fileName", "apiKey", "forceRefresh"],
  );

  @override
  Future<OcrResult> crateApiOcrProcessPdf({
    required String docId,
    required String fileName,
    required String apiKey,
    required bool forceRefresh,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          sse_encode_String(fileName, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_bool(forceRefresh, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ocr_result,
          decodeErrorData: sse_decode_ocr_error,
        ),
        constMeta: kCrateApiOcrProcessPdfConstMeta,
        argValues: [docId, fileName, apiKey, forceRefresh],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOcrProcessPdfConstMeta => const TaskConstMeta(
    debugName: "process_pdf",
    argNames: ["docId", "fileName", "apiKey", "forceRefresh"],
  );

  @override
  Future<void> crateApiStorageSaveNote({
    required String pageId,
    required Note note,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pageId, serializer);
          sse_encode_box_autoadd_note(note, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageSaveNoteConstMeta,
        argValues: [pageId, note],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageSaveNoteConstMeta =>
      const TaskConstMeta(debugName: "save_note", argNames: ["pageId", "note"]);

  @override
  Future<void> crateApiStorageSavePaperBook({required PaperBook book}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_paper_book(book, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageSavePaperBookConstMeta,
        argValues: [book],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageSavePaperBookConstMeta =>
      const TaskConstMeta(debugName: "save_paper_book", argNames: ["book"]);

  @override
  Future<void> crateApiStorageSavePdfDoc({required PdfDoc doc}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pdf_doc(doc, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageSavePdfDocConstMeta,
        argValues: [doc],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageSavePdfDocConstMeta =>
      const TaskConstMeta(debugName: "save_pdf_doc", argNames: ["doc"]);

  @override
  Future<void> crateApiStorageUpsertPaperPage({
    required String bookId,
    required PaperPage page,
    required String updatedAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bookId, serializer);
          sse_encode_box_autoadd_paper_page(page, serializer);
          sse_encode_String(updatedAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_storage_error,
        ),
        constMeta: kCrateApiStorageUpsertPaperPageConstMeta,
        argValues: [bookId, page, updatedAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageUpsertPaperPageConstMeta =>
      const TaskConstMeta(
        debugName: "upsert_paper_page",
        argNames: ["bookId", "page", "updatedAt"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_note(raw);
  }

  @protected
  PaperBook dco_decode_box_autoadd_paper_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_paper_book(raw);
  }

  @protected
  PaperPage dco_decode_box_autoadd_paper_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_paper_page(raw);
  }

  @protected
  PdfDoc dco_decode_box_autoadd_pdf_doc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pdf_doc(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Note> dco_decode_list_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note).toList();
  }

  @protected
  List<OcrPage> dco_decode_list_ocr_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ocr_page).toList();
  }

  @protected
  List<PaperBook> dco_decode_list_paper_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_paper_book).toList();
  }

  @protected
  List<PaperPage> dco_decode_list_paper_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_paper_page).toList();
  }

  @protected
  List<PdfDoc> dco_decode_list_pdf_doc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pdf_doc).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Note dco_decode_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return Note(
      id: dco_decode_String(arr[0]),
      pageId: dco_decode_String(arr[1]),
      selectedText: dco_decode_String(arr[2]),
      startOffset: dco_decode_opt_box_autoadd_i_32(arr[3]),
      endOffset: dco_decode_opt_box_autoadd_i_32(arr[4]),
      content: dco_decode_String(arr[5]),
      tags: dco_decode_list_String(arr[6]),
      createdAt: dco_decode_String(arr[7]),
      updatedAt: dco_decode_String(arr[8]),
    );
  }

  @protected
  OcrError dco_decode_ocr_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return OcrError_NetworkError(dco_decode_String(raw[1]));
      case 1:
        return OcrError_TimeoutError();
      case 2:
        return OcrError_ApiKeyError();
      case 3:
        return OcrError_FileSizeError(dco_decode_String(raw[1]));
      case 4:
        return OcrError_DocumentError(dco_decode_String(raw[1]));
      case 5:
        return OcrError_ParseError(dco_decode_String(raw[1]));
      case 6:
        return OcrError_RateLimitError();
      case 7:
        return OcrError_StorageError(dco_decode_String(raw[1]));
      case 8:
        return OcrError_UnknownError(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  OcrPage dco_decode_ocr_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OcrPage(
      index: dco_decode_i_32(arr[0]),
      markdown: dco_decode_String(arr[1]),
    );
  }

  @protected
  OcrResult dco_decode_ocr_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OcrResult(
      pages: dco_decode_list_ocr_page(arr[0]),
      sourceHash: dco_decode_String(arr[1]),
      cacheHit: dco_decode_bool(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PaperBook dco_decode_paper_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PaperBook(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
      updatedAt: dco_decode_String(arr[3]),
      pages: dco_decode_list_paper_page(arr[4]),
    );
  }

  @protected
  PaperBooksData dco_decode_paper_books_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PaperBooksData(
      version: dco_decode_u_32(arr[0]),
      books: dco_decode_list_paper_book(arr[1]),
    );
  }

  @protected
  PaperPage dco_decode_paper_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PaperPage(
      id: dco_decode_String(arr[0]),
      imagePath: dco_decode_String(arr[1]),
      pageLabel: dco_decode_opt_String(arr[2]),
      ocrHash: dco_decode_String(arr[3]),
      markdown: dco_decode_String(arr[4]),
      notes: dco_decode_list_note(arr[5]),
    );
  }

  @protected
  PdfDoc dco_decode_pdf_doc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return PdfDoc(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      originalFileName: dco_decode_String(arr[2]),
      pdfPath: dco_decode_String(arr[3]),
      markdownPath: dco_decode_String(arr[4]),
      ocrHash: dco_decode_String(arr[5]),
      pageCount: dco_decode_i_32(arr[6]),
      lastReadPageIndex: dco_decode_i_32(arr[7]),
      tags: dco_decode_list_String(arr[8]),
      createdAt: dco_decode_String(arr[9]),
      updatedAt: dco_decode_String(arr[10]),
    );
  }

  @protected
  PdfDocsData dco_decode_pdf_docs_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PdfDocsData(
      version: dco_decode_u_32(arr[0]),
      docs: dco_decode_list_pdf_doc(arr[1]),
    );
  }

  @protected
  StorageError dco_decode_storage_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StorageError_NotInitialized();
      case 1:
        return StorageError_NotFound(dco_decode_String(raw[1]));
      case 2:
        return StorageError_IoError(dco_decode_String(raw[1]));
      case 3:
        return StorageError_JsonError(dco_decode_String(raw[1]));
      case 4:
        return StorageError_ValidationError(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_note(deserializer));
  }

  @protected
  PaperBook sse_decode_box_autoadd_paper_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_paper_book(deserializer));
  }

  @protected
  PaperPage sse_decode_box_autoadd_paper_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_paper_page(deserializer));
  }

  @protected
  PdfDoc sse_decode_box_autoadd_pdf_doc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pdf_doc(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Note>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note(deserializer));
    }
    return ans_;
  }

  @protected
  List<OcrPage> sse_decode_list_ocr_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OcrPage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ocr_page(deserializer));
    }
    return ans_;
  }

  @protected
  List<PaperBook> sse_decode_list_paper_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PaperBook>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_paper_book(deserializer));
    }
    return ans_;
  }

  @protected
  List<PaperPage> sse_decode_list_paper_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PaperPage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_paper_page(deserializer));
    }
    return ans_;
  }

  @protected
  List<PdfDoc> sse_decode_list_pdf_doc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PdfDoc>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pdf_doc(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Note sse_decode_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_pageId = sse_decode_String(deserializer);
    var var_selectedText = sse_decode_String(deserializer);
    var var_startOffset = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_endOffset = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return Note(
      id: var_id,
      pageId: var_pageId,
      selectedText: var_selectedText,
      startOffset: var_startOffset,
      endOffset: var_endOffset,
      content: var_content,
      tags: var_tags,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  OcrError sse_decode_ocr_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return OcrError_NetworkError(var_field0);
      case 1:
        return OcrError_TimeoutError();
      case 2:
        return OcrError_ApiKeyError();
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return OcrError_FileSizeError(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return OcrError_DocumentError(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return OcrError_ParseError(var_field0);
      case 6:
        return OcrError_RateLimitError();
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return OcrError_StorageError(var_field0);
      case 8:
        var var_field0 = sse_decode_String(deserializer);
        return OcrError_UnknownError(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  OcrPage sse_decode_ocr_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_i_32(deserializer);
    var var_markdown = sse_decode_String(deserializer);
    return OcrPage(index: var_index, markdown: var_markdown);
  }

  @protected
  OcrResult sse_decode_ocr_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pages = sse_decode_list_ocr_page(deserializer);
    var var_sourceHash = sse_decode_String(deserializer);
    var var_cacheHit = sse_decode_bool(deserializer);
    return OcrResult(
      pages: var_pages,
      sourceHash: var_sourceHash,
      cacheHit: var_cacheHit,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PaperBook sse_decode_paper_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_pages = sse_decode_list_paper_page(deserializer);
    return PaperBook(
      id: var_id,
      title: var_title,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      pages: var_pages,
    );
  }

  @protected
  PaperBooksData sse_decode_paper_books_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_32(deserializer);
    var var_books = sse_decode_list_paper_book(deserializer);
    return PaperBooksData(version: var_version, books: var_books);
  }

  @protected
  PaperPage sse_decode_paper_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_imagePath = sse_decode_String(deserializer);
    var var_pageLabel = sse_decode_opt_String(deserializer);
    var var_ocrHash = sse_decode_String(deserializer);
    var var_markdown = sse_decode_String(deserializer);
    var var_notes = sse_decode_list_note(deserializer);
    return PaperPage(
      id: var_id,
      imagePath: var_imagePath,
      pageLabel: var_pageLabel,
      ocrHash: var_ocrHash,
      markdown: var_markdown,
      notes: var_notes,
    );
  }

  @protected
  PdfDoc sse_decode_pdf_doc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_originalFileName = sse_decode_String(deserializer);
    var var_pdfPath = sse_decode_String(deserializer);
    var var_markdownPath = sse_decode_String(deserializer);
    var var_ocrHash = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_i_32(deserializer);
    var var_lastReadPageIndex = sse_decode_i_32(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return PdfDoc(
      id: var_id,
      title: var_title,
      originalFileName: var_originalFileName,
      pdfPath: var_pdfPath,
      markdownPath: var_markdownPath,
      ocrHash: var_ocrHash,
      pageCount: var_pageCount,
      lastReadPageIndex: var_lastReadPageIndex,
      tags: var_tags,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  PdfDocsData sse_decode_pdf_docs_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_32(deserializer);
    var var_docs = sse_decode_list_pdf_doc(deserializer);
    return PdfDocsData(version: var_version, docs: var_docs);
  }

  @protected
  StorageError sse_decode_storage_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return StorageError_NotInitialized();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return StorageError_NotFound(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return StorageError_IoError(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return StorageError_JsonError(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return StorageError_ValidationError(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_paper_book(
    PaperBook self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_paper_book(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_paper_page(
    PaperPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_paper_page(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pdf_doc(PdfDoc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pdf_doc(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ocr_page(List<OcrPage> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ocr_page(item, serializer);
    }
  }

  @protected
  void sse_encode_list_paper_book(
    List<PaperBook> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_paper_book(item, serializer);
    }
  }

  @protected
  void sse_encode_list_paper_page(
    List<PaperPage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_paper_page(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pdf_doc(List<PdfDoc> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pdf_doc(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_note(Note self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.pageId, serializer);
    sse_encode_String(self.selectedText, serializer);
    sse_encode_opt_box_autoadd_i_32(self.startOffset, serializer);
    sse_encode_opt_box_autoadd_i_32(self.endOffset, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_ocr_error(OcrError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case OcrError_NetworkError(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case OcrError_TimeoutError():
        sse_encode_i_32(1, serializer);
      case OcrError_ApiKeyError():
        sse_encode_i_32(2, serializer);
      case OcrError_FileSizeError(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case OcrError_DocumentError(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case OcrError_ParseError(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case OcrError_RateLimitError():
        sse_encode_i_32(6, serializer);
      case OcrError_StorageError(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case OcrError_UnknownError(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_ocr_page(OcrPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
    sse_encode_String(self.markdown, serializer);
  }

  @protected
  void sse_encode_ocr_result(OcrResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_ocr_page(self.pages, serializer);
    sse_encode_String(self.sourceHash, serializer);
    sse_encode_bool(self.cacheHit, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_paper_book(PaperBook self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_list_paper_page(self.pages, serializer);
  }

  @protected
  void sse_encode_paper_books_data(
    PaperBooksData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.version, serializer);
    sse_encode_list_paper_book(self.books, serializer);
  }

  @protected
  void sse_encode_paper_page(PaperPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.imagePath, serializer);
    sse_encode_opt_String(self.pageLabel, serializer);
    sse_encode_String(self.ocrHash, serializer);
    sse_encode_String(self.markdown, serializer);
    sse_encode_list_note(self.notes, serializer);
  }

  @protected
  void sse_encode_pdf_doc(PdfDoc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.originalFileName, serializer);
    sse_encode_String(self.pdfPath, serializer);
    sse_encode_String(self.markdownPath, serializer);
    sse_encode_String(self.ocrHash, serializer);
    sse_encode_i_32(self.pageCount, serializer);
    sse_encode_i_32(self.lastReadPageIndex, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_pdf_docs_data(PdfDocsData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.version, serializer);
    sse_encode_list_pdf_doc(self.docs, serializer);
  }

  @protected
  void sse_encode_storage_error(StorageError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StorageError_NotInitialized():
        sse_encode_i_32(0, serializer);
      case StorageError_NotFound(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case StorageError_IoError(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case StorageError_JsonError(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case StorageError_ValidationError(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
