// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/models.dart';
import 'api/ocr.dart';
import 'api/storage.dart';
import 'api/vocab.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ReqwestChatClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClientPtr;

  @protected
  ReqwestChatClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    dynamic raw,
  );

  @protected
  ReqwestChatClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  ReqwestChatClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  MistralChatClient dco_decode_TraitDef_MistralChatClient(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  Note dco_decode_box_autoadd_note(dynamic raw);

  @protected
  PaperBook dco_decode_box_autoadd_paper_book(dynamic raw);

  @protected
  PaperPage dco_decode_box_autoadd_paper_page(dynamic raw);

  @protected
  PdfDoc dco_decode_box_autoadd_pdf_doc(dynamic raw);

  @protected
  PdfNote dco_decode_box_autoadd_pdf_note(dynamic raw);

  @protected
  VocabEncounter dco_decode_box_autoadd_vocab_encounter(dynamic raw);

  @protected
  VocabEntry dco_decode_box_autoadd_vocab_entry(dynamic raw);

  @protected
  VocabSource dco_decode_box_autoadd_vocab_source(dynamic raw);

  @protected
  VocabSourceFilter dco_decode_box_autoadd_vocab_source_filter(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Note> dco_decode_list_note(dynamic raw);

  @protected
  List<OcrPage> dco_decode_list_ocr_page(dynamic raw);

  @protected
  List<PaperBook> dco_decode_list_paper_book(dynamic raw);

  @protected
  List<PaperPage> dco_decode_list_paper_page(dynamic raw);

  @protected
  List<PdfDoc> dco_decode_list_pdf_doc(dynamic raw);

  @protected
  List<PdfNote> dco_decode_list_pdf_note(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<VocabEncounter> dco_decode_list_vocab_encounter(dynamic raw);

  @protected
  List<VocabEntry> dco_decode_list_vocab_entry(dynamic raw);

  @protected
  Note dco_decode_note(dynamic raw);

  @protected
  OcrError dco_decode_ocr_error(dynamic raw);

  @protected
  OcrPage dco_decode_ocr_page(dynamic raw);

  @protected
  OcrResult dco_decode_ocr_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PaperBook dco_decode_paper_book(dynamic raw);

  @protected
  PaperBooksData dco_decode_paper_books_data(dynamic raw);

  @protected
  PaperPage dco_decode_paper_page(dynamic raw);

  @protected
  PdfDoc dco_decode_pdf_doc(dynamic raw);

  @protected
  PdfDocsData dco_decode_pdf_docs_data(dynamic raw);

  @protected
  PdfManualMarkdownData dco_decode_pdf_manual_markdown_data(dynamic raw);

  @protected
  PdfNote dco_decode_pdf_note(dynamic raw);

  @protected
  PdfNotesData dco_decode_pdf_notes_data(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  StorageError dco_decode_storage_error(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VocabData dco_decode_vocab_data(dynamic raw);

  @protected
  VocabEncounter dco_decode_vocab_encounter(dynamic raw);

  @protected
  VocabEntry dco_decode_vocab_entry(dynamic raw);

  @protected
  VocabError dco_decode_vocab_error(dynamic raw);

  @protected
  VocabLookupResult dco_decode_vocab_lookup_result(dynamic raw);

  @protected
  VocabSource dco_decode_vocab_source(dynamic raw);

  @protected
  VocabSourceFilter dco_decode_vocab_source_filter(dynamic raw);

  @protected
  ReqwestChatClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    SseDeserializer deserializer,
  );

  @protected
  ReqwestChatClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  ReqwestChatClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  Note sse_decode_box_autoadd_note(SseDeserializer deserializer);

  @protected
  PaperBook sse_decode_box_autoadd_paper_book(SseDeserializer deserializer);

  @protected
  PaperPage sse_decode_box_autoadd_paper_page(SseDeserializer deserializer);

  @protected
  PdfDoc sse_decode_box_autoadd_pdf_doc(SseDeserializer deserializer);

  @protected
  PdfNote sse_decode_box_autoadd_pdf_note(SseDeserializer deserializer);

  @protected
  VocabEncounter sse_decode_box_autoadd_vocab_encounter(
    SseDeserializer deserializer,
  );

  @protected
  VocabEntry sse_decode_box_autoadd_vocab_entry(SseDeserializer deserializer);

  @protected
  VocabSource sse_decode_box_autoadd_vocab_source(SseDeserializer deserializer);

  @protected
  VocabSourceFilter sse_decode_box_autoadd_vocab_source_filter(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer);

  @protected
  List<OcrPage> sse_decode_list_ocr_page(SseDeserializer deserializer);

  @protected
  List<PaperBook> sse_decode_list_paper_book(SseDeserializer deserializer);

  @protected
  List<PaperPage> sse_decode_list_paper_page(SseDeserializer deserializer);

  @protected
  List<PdfDoc> sse_decode_list_pdf_doc(SseDeserializer deserializer);

  @protected
  List<PdfNote> sse_decode_list_pdf_note(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<VocabEncounter> sse_decode_list_vocab_encounter(
    SseDeserializer deserializer,
  );

  @protected
  List<VocabEntry> sse_decode_list_vocab_entry(SseDeserializer deserializer);

  @protected
  Note sse_decode_note(SseDeserializer deserializer);

  @protected
  OcrError sse_decode_ocr_error(SseDeserializer deserializer);

  @protected
  OcrPage sse_decode_ocr_page(SseDeserializer deserializer);

  @protected
  OcrResult sse_decode_ocr_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PaperBook sse_decode_paper_book(SseDeserializer deserializer);

  @protected
  PaperBooksData sse_decode_paper_books_data(SseDeserializer deserializer);

  @protected
  PaperPage sse_decode_paper_page(SseDeserializer deserializer);

  @protected
  PdfDoc sse_decode_pdf_doc(SseDeserializer deserializer);

  @protected
  PdfDocsData sse_decode_pdf_docs_data(SseDeserializer deserializer);

  @protected
  PdfManualMarkdownData sse_decode_pdf_manual_markdown_data(
    SseDeserializer deserializer,
  );

  @protected
  PdfNote sse_decode_pdf_note(SseDeserializer deserializer);

  @protected
  PdfNotesData sse_decode_pdf_notes_data(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  StorageError sse_decode_storage_error(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VocabData sse_decode_vocab_data(SseDeserializer deserializer);

  @protected
  VocabEncounter sse_decode_vocab_encounter(SseDeserializer deserializer);

  @protected
  VocabEntry sse_decode_vocab_entry(SseDeserializer deserializer);

  @protected
  VocabError sse_decode_vocab_error(SseDeserializer deserializer);

  @protected
  VocabLookupResult sse_decode_vocab_lookup_result(
    SseDeserializer deserializer,
  );

  @protected
  VocabSource sse_decode_vocab_source(SseDeserializer deserializer);

  @protected
  VocabSourceFilter sse_decode_vocab_source_filter(
    SseDeserializer deserializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    ReqwestChatClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    ReqwestChatClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    ReqwestChatClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_paper_book(
    PaperBook self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_paper_page(
    PaperPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pdf_doc(PdfDoc self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pdf_note(PdfNote self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vocab_encounter(
    VocabEncounter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_vocab_entry(
    VocabEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_vocab_source(
    VocabSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_vocab_source_filter(
    VocabSourceFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ocr_page(List<OcrPage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_paper_book(
    List<PaperBook> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_paper_page(
    List<PaperPage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pdf_doc(List<PdfDoc> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pdf_note(List<PdfNote> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vocab_encounter(
    List<VocabEncounter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vocab_entry(
    List<VocabEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note(Note self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_error(OcrError self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_page(OcrPage self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_result(OcrResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_paper_book(PaperBook self, SseSerializer serializer);

  @protected
  void sse_encode_paper_books_data(
    PaperBooksData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paper_page(PaperPage self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_doc(PdfDoc self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_docs_data(PdfDocsData self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_manual_markdown_data(
    PdfManualMarkdownData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_note(PdfNote self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_notes_data(PdfNotesData self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_error(StorageError self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vocab_data(VocabData self, SseSerializer serializer);

  @protected
  void sse_encode_vocab_encounter(
    VocabEncounter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vocab_entry(VocabEntry self, SseSerializer serializer);

  @protected
  void sse_encode_vocab_error(VocabError self, SseSerializer serializer);

  @protected
  void sse_encode_vocab_lookup_result(
    VocabLookupResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vocab_source(VocabSource self, SseSerializer serializer);

  @protected
  void sse_encode_vocab_source_filter(
    VocabSourceFilter self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_brrk_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_brrk_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReqwestChatClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
