// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `validate_relative_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CacheRecord`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// A note attached to a specific page.
class Note {
  final String id;

  /// The page this note belongs to.
  final String pageId;

  /// The text that was selected when the note was created.
  final String selectedText;

  /// Byte offset of selection start in the page's markdown.
  final int? startOffset;

  /// Byte offset of selection end in the page's markdown.
  final int? endOffset;

  /// User-authored text content.
  final String content;

  /// Optional tag strings.
  final List<String> tags;
  final String createdAt;
  final String updatedAt;

  const Note({
    required this.id,
    required this.pageId,
    required this.selectedText,
    this.startOffset,
    this.endOffset,
    required this.content,
    required this.tags,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pageId.hashCode ^
      selectedText.hashCode ^
      startOffset.hashCode ^
      endOffset.hashCode ^
      content.hashCode ^
      tags.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pageId == other.pageId &&
          selectedText == other.selectedText &&
          startOffset == other.startOffset &&
          endOffset == other.endOffset &&
          content == other.content &&
          tags == other.tags &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

@freezed
sealed class OcrError with _$OcrError implements FrbException {
  const OcrError._();

  const factory OcrError.networkError(String field0) = OcrError_NetworkError;
  const factory OcrError.timeoutError() = OcrError_TimeoutError;
  const factory OcrError.apiKeyError() = OcrError_ApiKeyError;
  const factory OcrError.fileSizeError(String field0) = OcrError_FileSizeError;

  /// Unreadable PDF, corrupt image, or unsupported format.
  const factory OcrError.documentError(String field0) = OcrError_DocumentError;
  const factory OcrError.parseError(String field0) = OcrError_ParseError;
  const factory OcrError.rateLimitError() = OcrError_RateLimitError;
  const factory OcrError.storageError(String field0) = OcrError_StorageError;
  const factory OcrError.unknownError(String field0) = OcrError_UnknownError;
}

/// A single OCR page.
class OcrPage {
  /// 0-based page index matching the Mistral API response order.
  final int index;

  /// Extracted text in Markdown format.
  final String markdown;

  const OcrPage({required this.index, required this.markdown});

  @override
  int get hashCode => index.hashCode ^ markdown.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrPage &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          markdown == other.markdown;
}

/// Result of an OCR operation. Returned to Dart via flutter_rust_bridge.
class OcrResult {
  /// All pages extracted from the source.
  final List<OcrPage> pages;

  /// SHA-256 hash of the source bytes, prefixed "sha256:".
  final String sourceHash;

  /// True when the result was served from cache without calling the Mistral API.
  final bool cacheHit;

  const OcrResult({
    required this.pages,
    required this.sourceHash,
    required this.cacheHit,
  });

  @override
  int get hashCode => pages.hashCode ^ sourceHash.hashCode ^ cacheHit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrResult &&
          runtimeType == other.runtimeType &&
          pages == other.pages &&
          sourceHash == other.sourceHash &&
          cacheHit == other.cacheHit;
}

/// A paper book containing one or more captured pages.
class PaperBook {
  final String id;
  final String title;
  final String createdAt;
  final String updatedAt;
  final List<PaperPage> pages;

  const PaperBook({
    required this.id,
    required this.title,
    required this.createdAt,
    required this.updatedAt,
    required this.pages,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaperBook &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          pages == other.pages;
}

/// Top-level container for all paper books.
class PaperBooksData {
  final int version;
  final List<PaperBook> books;

  const PaperBooksData({required this.version, required this.books});

  static Future<PaperBooksData> default_() =>
      RustLib.instance.api.crateApiModelsPaperBooksDataDefault();

  @override
  int get hashCode => version.hashCode ^ books.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaperBooksData &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          books == other.books;
}

/// A single page inside a paper book.
class PaperPage {
  final String id;

  /// Relative path from data_dir to the captured image.
  final String imagePath;

  /// Optional display label (e.g. "42", "xii"). Trimmed, max 32 chars. Does not affect order.
  final String? pageLabel;

  /// SHA-256 hash used for cache lookup.
  final String ocrHash;

  /// Extracted Markdown text.
  final String markdown;

  /// User-edited Markdown. If `Some(_)`, the reader uses this text instead of
  /// `markdown`. The original OCR Markdown is preserved for "Reset to OCR".
  /// Capped at 10,000 chars.
  final String? manualMarkdown;
  final List<Note> notes;

  const PaperPage({
    required this.id,
    required this.imagePath,
    this.pageLabel,
    required this.ocrHash,
    required this.markdown,
    this.manualMarkdown,
    required this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      imagePath.hashCode ^
      pageLabel.hashCode ^
      ocrHash.hashCode ^
      markdown.hashCode ^
      manualMarkdown.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaperPage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          imagePath == other.imagePath &&
          pageLabel == other.pageLabel &&
          ocrHash == other.ocrHash &&
          markdown == other.markdown &&
          manualMarkdown == other.manualMarkdown &&
          notes == other.notes;
}

/// A PDF document with OCR metadata.
class PdfDoc {
  final String id;
  final String title;

  /// Original file name selected by the user.
  final String originalFileName;

  /// Relative path to the stored PDF copy.
  final String pdfPath;

  /// Relative path to the generated Markdown.
  final String markdownPath;

  /// SHA-256 hash used for cache lookup.
  final String ocrHash;

  /// Total number of pages reported by Mistral OCR.
  final int pageCount;

  /// Last read page index (0-based), for resume.
  final int lastReadPageIndex;
  final List<String> tags;
  final String createdAt;
  final String updatedAt;

  const PdfDoc({
    required this.id,
    required this.title,
    required this.originalFileName,
    required this.pdfPath,
    required this.markdownPath,
    required this.ocrHash,
    required this.pageCount,
    required this.lastReadPageIndex,
    required this.tags,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      originalFileName.hashCode ^
      pdfPath.hashCode ^
      markdownPath.hashCode ^
      ocrHash.hashCode ^
      pageCount.hashCode ^
      lastReadPageIndex.hashCode ^
      tags.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfDoc &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          originalFileName == other.originalFileName &&
          pdfPath == other.pdfPath &&
          markdownPath == other.markdownPath &&
          ocrHash == other.ocrHash &&
          pageCount == other.pageCount &&
          lastReadPageIndex == other.lastReadPageIndex &&
          tags == other.tags &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Top-level container for all PDF documents.
class PdfDocsData {
  final int version;
  final List<PdfDoc> docs;

  const PdfDocsData({required this.version, required this.docs});

  static Future<PdfDocsData> default_() =>
      RustLib.instance.api.crateApiModelsPdfDocsDataDefault();

  @override
  int get hashCode => version.hashCode ^ docs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfDocsData &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          docs == other.docs;
}

/// Per-PDF page Markdown overrides.
///
/// Stored at `{data_dir}/pdf/{doc_id}/manual.json`.
/// Keys are 0-based page indices as strings.
/// Empty/whitespace manual text is normalized to absent (key removed).
class PdfManualMarkdownData {
  final int version;
  final Map<String, String> pages;

  const PdfManualMarkdownData({required this.version, required this.pages});

  static Future<PdfManualMarkdownData> default_() =>
      RustLib.instance.api.crateApiModelsPdfManualMarkdownDataDefault();

  @override
  int get hashCode => version.hashCode ^ pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfManualMarkdownData &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          pages == other.pages;
}

@freezed
sealed class StorageError with _$StorageError implements FrbException {
  const StorageError._();

  /// App has not been initialized with a data directory yet.
  const factory StorageError.notInitialized() = StorageError_NotInitialized;

  /// The requested entity was not found in storage.
  const factory StorageError.notFound(String field0) = StorageError_NotFound;

  /// A filesystem I/O error occurred.
  const factory StorageError.ioError(String field0) = StorageError_IoError;

  /// JSON parse or serialization failed.
  const factory StorageError.jsonError(String field0) = StorageError_JsonError;

  /// A validation check (e.g. path traversal) failed.
  const factory StorageError.validationError(String field0) =
      StorageError_ValidationError;
}
