// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_mistral_image_request`, `build_mistral_pdf_request`, `call_mistral_http`, `call_mistral_image`, `call_mistral_pdf`, `classify_error`, `generate_markdown_with_page_markers`, `parse_mistral_response`, `save_pdf_markdown`, `sha256_hex`, `validate_image_header`, `validate_pdf_header`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DocumentPayload`, `MistralError`, `MistralImageRequest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Image OCR with integrated caching.
///
/// ## Arguments
/// - `base64_data`: Base64-encoded image bytes (JPEG/PNG/WebP/etc.)
/// - `_file_name`: Original file name for cache record metadata
/// - `api_key`: Mistral API key — not stored, not logged
/// - `force_refresh`: If true, bypass cache and call the Mistral API directly
///
/// ## Returns
/// `Result<OcrResult, OcrError>` — callers handle errors via the classification
/// in SPEC.md Section 3.7 F7.
Future<OcrResult> processImage({
  required String base64Data,
  required String fileName,
  required String apiKey,
  required bool forceRefresh,
}) => RustLib.instance.api.crateApiOcrProcessImage(
  base64Data: base64Data,
  fileName: fileName,
  apiKey: apiKey,
  forceRefresh: forceRefresh,
);

/// PDF OCR with integrated caching.
///
/// ## Arguments
/// - `doc_id`: UUID identifying the PDF document stored at `{data_dir}/pdfs/{doc_id}.pdf`
/// - `_file_name`: Original file name for cache record metadata
/// - `api_key`: Mistral API key — not stored, not logged
/// - `force_refresh`: If true, bypass cache and call the Mistral API directly
///
/// ## Returns
/// `Result<OcrResult, OcrError>`
Future<OcrResult> processPdf({
  required String docId,
  required String fileName,
  required String apiKey,
  required bool forceRefresh,
}) => RustLib.instance.api.crateApiOcrProcessPdf(
  docId: docId,
  fileName: fileName,
  apiKey: apiKey,
  forceRefresh: forceRefresh,
);
