// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_vocab_marker`

/// Must be called once at app start with the application's data directory path.
/// Creates required subdirectories if missing.
void initApp({required String dataDir}) =>
    RustLib.instance.api.crateApiStorageInitApp(dataDir: dataDir);

/// Saves or updates a paper book (create or rename).
Future<void> savePaperBook({required PaperBook book}) =>
    RustLib.instance.api.crateApiStorageSavePaperBook(book: book);

/// Returns all paper books.
Future<PaperBooksData> getPaperBooks() =>
    RustLib.instance.api.crateApiStorageGetPaperBooks();

/// Deletes a paper book, its images, and unreferenced cache entries.
Future<void> deletePaperBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeletePaperBook(bookId: bookId);

/// Inserts or replaces a page in a paper book.
Future<void> upsertPaperPage({
  required String bookId,
  required PaperPage page,
  required String updatedAt,
}) => RustLib.instance.api.crateApiStorageUpsertPaperPage(
  bookId: bookId,
  page: page,
  updatedAt: updatedAt,
);

/// Removes a page from a paper book, including its image and embedded notes.
/// Removes unreferenced paper OCR cache entry.
Future<void> deletePaperPage({
  required String bookId,
  required String pageId,
  required String updatedAt,
}) => RustLib.instance.api.crateApiStorageDeletePaperPage(
  bookId: bookId,
  pageId: pageId,
  updatedAt: updatedAt,
);

/// Saves or updates a PDF document.
Future<void> savePdfDoc({required PdfDoc doc}) =>
    RustLib.instance.api.crateApiStorageSavePdfDoc(doc: doc);

/// Returns all PDF documents.
Future<PdfDocsData> getPdfDocs() =>
    RustLib.instance.api.crateApiStorageGetPdfDocs();

/// Attaches or updates a note on a specific page.
Future<void> saveNote({required String pageId, required Note note}) =>
    RustLib.instance.api.crateApiStorageSaveNote(pageId: pageId, note: note);

/// Deletes a note from a specific page.
Future<void> deleteNote({required String pageId, required String noteId}) =>
    RustLib.instance.api.crateApiStorageDeleteNote(
      pageId: pageId,
      noteId: noteId,
    );

/// Returns the Markdown content for a PDF document.
Future<String> getPdfMarkdown({required String docId}) =>
    RustLib.instance.api.crateApiStorageGetPdfMarkdown(docId: docId);

/// Deletes a PDF document, its file, markdown, and unreferenced cache entry.
Future<void> deletePdfDoc({required String docId}) =>
    RustLib.instance.api.crateApiStorageDeletePdfDoc(docId: docId);

/// Clears all OCR cache entries and returns the total count removed.
Future<int> clearOcrCache() =>
    RustLib.instance.api.crateApiStorageClearOcrCache();

/// Persists a manual Markdown override for a paper page.
/// `None` or whitespace clears the override.
Future<void> savePaperPageManualMarkdown({
  required String bookId,
  required String pageId,
  String? manualMarkdown,
  required String updatedAt,
}) => RustLib.instance.api.crateApiStorageSavePaperPageManualMarkdown(
  bookId: bookId,
  pageId: pageId,
  manualMarkdown: manualMarkdown,
  updatedAt: updatedAt,
);

/// Returns all manual Markdown overrides for a PDF. Returns an empty struct
/// if no manual file exists yet.
Future<PdfManualMarkdownData> getPdfManualMarkdown({required String docId}) =>
    RustLib.instance.api.crateApiStorageGetPdfManualMarkdown(docId: docId);

/// Persists or clears a manual Markdown override for one PDF page.
/// `page_index` is 0-based. `None` or whitespace clears the override.
Future<void> savePdfPageManualMarkdown({
  required String docId,
  required int pageIndex,
  String? manualMarkdown,
}) => RustLib.instance.api.crateApiStorageSavePdfPageManualMarkdown(
  docId: docId,
  pageIndex: pageIndex,
  manualMarkdown: manualMarkdown,
);

/// Saves or updates a note attached to a specific PDF page.
Future<void> savePdfNote({required PdfNote note}) =>
    RustLib.instance.api.crateApiStorageSavePdfNote(note: note);

/// Returns PDF notes for a doc, optionally filtered by 0-based page index.
Future<List<PdfNote>> getPdfNotes({required String docId, int? pageIndex}) =>
    RustLib.instance.api.crateApiStorageGetPdfNotes(
      docId: docId,
      pageIndex: pageIndex,
    );

/// Deletes a note from a PDF.
Future<void> deletePdfNote({required String docId, required String noteId}) =>
    RustLib.instance.api.crateApiStorageDeletePdfNote(
      docId: docId,
      noteId: noteId,
    );

/// Returns all vocabulary entries, optionally filtered by source.
Future<List<VocabEntry>> listVocabulary({
  required VocabSourceFilter sourceFilter,
}) => RustLib.instance.api.crateApiStorageListVocabulary(
  sourceFilter: sourceFilter,
);

/// Edits the definition for an existing vocabulary entry and sets the
/// `definition_edited` flag.
Future<void> updateVocabularyDefinition({
  required String language,
  required String lemma,
  required String definition,
}) => RustLib.instance.api.crateApiStorageUpdateVocabularyDefinition(
  language: language,
  lemma: lemma,
  definition: definition,
);

/// Deletes a vocabulary entry and all of its encounters.
Future<void> deleteVocabularyEntry({
  required String language,
  required String lemma,
}) => RustLib.instance.api.crateApiStorageDeleteVocabularyEntry(
  language: language,
  lemma: lemma,
);

/// Deletes one encounter from a vocabulary entry. If the entry has no
/// encounters left, the entry itself is deleted.
Future<void> deleteVocabularyEncounter({
  required String language,
  required String lemma,
  required String encounterId,
}) => RustLib.instance.api.crateApiStorageDeleteVocabularyEncounter(
  language: language,
  lemma: lemma,
  encounterId: encounterId,
);

/// Persists a vocabulary lookup result (new entry or merge into existing).
Future<VocabLookupResult> saveVocabularyLookup({
  required VocabEntry entry,
  required VocabEncounter encounter,
}) => RustLib.instance.api.crateApiStorageSaveVocabularyLookup(
  entry: entry,
  encounter: encounter,
);

/// FRB wrapper: vocabulary lookup that calls Mistral Chat.
/// Implementation lives in `crate::api::vocab::lookup_vocabulary`.
Future<VocabLookupResult> lookupVocabulary({
  required String apiKey,
  required String selectedText,
  required String pageContext,
  int? selectionStart,
  int? selectionEnd,
  required VocabSource source,
}) => RustLib.instance.api.crateApiStorageLookupVocabulary(
  apiKey: apiKey,
  selectedText: selectedText,
  pageContext: pageContext,
  selectionStart: selectionStart,
  selectionEnd: selectionEnd,
  source: source,
);
