// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Must be called once at app start with the application's data directory path.
/// Creates required subdirectories if missing.
void initApp({required String dataDir}) =>
    RustLib.instance.api.crateApiStorageInitApp(dataDir: dataDir);

/// Saves or updates a paper book (create or rename).
Future<void> savePaperBook({required PaperBook book}) =>
    RustLib.instance.api.crateApiStorageSavePaperBook(book: book);

/// Returns all paper books.
Future<PaperBooksData> getPaperBooks() =>
    RustLib.instance.api.crateApiStorageGetPaperBooks();

/// Deletes a paper book, its images, and unreferenced cache entries.
Future<void> deletePaperBook({required String bookId}) =>
    RustLib.instance.api.crateApiStorageDeletePaperBook(bookId: bookId);

/// Inserts or replaces a page in a paper book.
Future<void> upsertPaperPage({
  required String bookId,
  required PaperPage page,
  required String updatedAt,
}) => RustLib.instance.api.crateApiStorageUpsertPaperPage(
  bookId: bookId,
  page: page,
  updatedAt: updatedAt,
);

/// Removes a page from a paper book, including its image and embedded notes.
/// Removes unreferenced paper OCR cache entry.
Future<void> deletePaperPage({
  required String bookId,
  required String pageId,
  required String updatedAt,
}) => RustLib.instance.api.crateApiStorageDeletePaperPage(
  bookId: bookId,
  pageId: pageId,
  updatedAt: updatedAt,
);

/// Saves or updates a PDF document.
Future<void> savePdfDoc({required PdfDoc doc}) =>
    RustLib.instance.api.crateApiStorageSavePdfDoc(doc: doc);

/// Returns all PDF documents.
Future<PdfDocsData> getPdfDocs() =>
    RustLib.instance.api.crateApiStorageGetPdfDocs();

/// Attaches or updates a note on a specific page.
Future<void> saveNote({required String pageId, required Note note}) =>
    RustLib.instance.api.crateApiStorageSaveNote(pageId: pageId, note: note);

/// Deletes a note from a specific page.
Future<void> deleteNote({required String pageId, required String noteId}) =>
    RustLib.instance.api.crateApiStorageDeleteNote(
      pageId: pageId,
      noteId: noteId,
    );

/// Returns the Markdown content for a PDF document.
Future<String> getPdfMarkdown({required String docId}) =>
    RustLib.instance.api.crateApiStorageGetPdfMarkdown(docId: docId);

/// Deletes a PDF document, its file, markdown, and unreferenced cache entry.
Future<void> deletePdfDoc({required String docId}) =>
    RustLib.instance.api.crateApiStorageDeletePdfDoc(docId: docId);

/// Clears all OCR cache entries and returns the total count removed.
Future<int> clearOcrCache() =>
    RustLib.instance.api.crateApiStorageClearOcrCache();
