// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_user_payload`, `ceil_char_boundary`, `classify_chat_error`, `detect_language`, `extract_chunk_around`, `extract_sentence`, `floor_char_boundary`, `is_valid_english_word`, `json_string`, `new_id`, `normalize_selection`, `parse_definition_content`, `parse_definition_response`, `strip_json_fences`, `trim_to_sentence`, `try_parse_definition_json`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ParsedDefinition`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<VocabLookupResult> lookupVocabulary({
  required String apiKey,
  required String selectedText,
  required String pageContext,
  int? selectionStart,
  int? selectionEnd,
  required VocabSource source,
}) => RustLib.instance.api.crateApiVocabLookupVocabulary(
  apiKey: apiKey,
  selectedText: selectedText,
  pageContext: pageContext,
  selectionStart: selectionStart,
  selectionEnd: selectionEnd,
  source: source,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReqwestChatClient>>
abstract class ReqwestChatClient
    implements RustOpaqueInterface, MistralChatClient {
  @override
  Future<String> chatCompletion({
    required String apiKey,
    required String systemPrompt,
    required String userPayload,
  });
}

abstract class MistralChatClient {
  Future<String> chatCompletion({
    required String apiKey,
    required String systemPrompt,
    required String userPayload,
  });
}
